(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Youjia, Welcome to Coot version 0.8.6.1")
(use-graphics-interface-state)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 186.30)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 12.60)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3m8b\3m8b.updated_refine_001.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8b/3m8b.updated_refine_001.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8b/3m8b.updated_refine_001.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3m8b\Polder_1\3m8b_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8b/Polder_1/3m8b_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(save-previous-map-colour 3)
(get-map-colour 3)
(graphics-molecule-bond-type 0)
(close-molecule 1)
(close-molecule 2)
(close-molecule 3)
(close-molecule 0)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3m8d\3m8d.updated_refine_001.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8d/3m8d.updated_refine_001.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8d/3m8d.updated_refine_001.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(save-previous-map-colour 5)
(get-map-colour 5)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3m8d\Polder_1\3m8d_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8d/Polder_1/3m8d_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(save-previous-map-colour 7)
(get-map-colour 7)
(graphics-molecule-bond-type 4)
(close-molecule 5)
(close-molecule 6)
(close-molecule 7)
(close-molecule 4)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final-version-data\3rgn\3rgn.updated_refine_001.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/3rgn/3rgn.updated_refine_001.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/3rgn/3rgn.updated_refine_001.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\3rgn\Polder_1\3rgn_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/3rgn/Polder_1/3rgn_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(save-previous-map-colour 9)
(get-map-colour 9)
(save-previous-map-colour 11)
(get-map-colour 11)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(graphics-molecule-bond-type 8)
(close-molecule 8)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final-version-data\3rgn\3rgn.updated_refine_001.pdb" 1)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(graphics-molecule-bond-type 12)
(close-molecule 12)
(close-molecule 9)
(close-molecule 10)
(close-molecule 11)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3v3x\3v3x.updated_refine_001.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3v3x/3v3x.updated_refine_001.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3v3x/3v3x.updated_refine_001.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(save-previous-map-colour 14)
(get-map-colour 14)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3v3x\Polder_1\3v3x_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3v3x/Polder_1/3v3x_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(save-previous-map-colour 16)
(get-map-colour 16)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3v3x\Polder_2\3v3x_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3v3x/Polder_2/3v3x_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(save-previous-map-colour 17)
(get-map-colour 17)
(graphics-molecule-bond-type 13)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3v3x\Polder_3\3v3x_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3v3x/Polder_3/3v3x_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(save-previous-map-colour 18)
(get-map-colour 18)
(close-molecule 14)
(close-molecule 15)
(close-molecule 16)
(close-molecule 17)
(close-molecule 18)
(close-molecule 13)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\5bmg\5bmg.updated_refine_001.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/5bmg/5bmg.updated_refine_001.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/5bmg/5bmg.updated_refine_001.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(save-previous-map-colour 20)
(get-map-colour 20)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\5bmg\Polder_1\5bmg_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/5bmg/Polder_1/5bmg_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(save-previous-map-colour 22)
(get-map-colour 22)
(graphics-molecule-bond-type 19)
(close-molecule 20)
(close-molecule 21)
(close-molecule 22)
(close-molecule 19)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\1zyt\1zyt.updated_refine_001.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/1zyt/1zyt.updated_refine_001.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/1zyt/1zyt.updated_refine_001.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\1zyt\Polder_1\1zyt_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/1zyt/Polder_1/1zyt_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(save-previous-map-colour 24)
(get-map-colour 24)
(save-previous-map-colour 26)
(get-map-colour 26)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(graphics-molecule-bond-type 23)
(close-molecule 24)
(close-molecule 25)
(close-molecule 26)
(close-molecule 23)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final-version-data\3ifx\3ifx.updated_refine_001.pdb" 1)
(graphics-molecule-bond-type 27)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/3ifx.updated_refine_001.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/3ifx.updated_refine_001.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(close-molecule 28)
(close-molecule 29)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/3ifx.updated_refine_001.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/3ifx.updated_refine_001.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\3ifx\Polder_1\3ifx_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/Polder_1/3ifx_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\3ifx\Polder_2\3ifx_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/Polder_2/3ifx_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(save-previous-map-colour 30)
(get-map-colour 30)
(save-previous-map-colour 32)
(get-map-colour 32)
(save-previous-map-colour 33)
(get-map-colour 33)
(graphics-molecule-bond-type 27)
(close-molecule 30)
(close-molecule 31)
(close-molecule 32)
(close-molecule 33)
(close-molecule 27)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final-version-data\5uui\5uui.updated_refine_001.pdb" 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/5uui/5uui.updated_refine_001.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/5uui/5uui.updated_refine_001.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(save-previous-map-colour 35)
(get-map-colour 35)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(manage-column-selector C:\Users\youjia\Desktop\MTN_final-version-data\5uui\Polder_1\5uui_polder_map_coeffs.mtz)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final-version-data/5uui/Polder_1/5uui_polder_map_coeffs.mtz" "/crystal/dataset/mFo-DFc_polder" "/crystal/dataset/PHImFo-DFc_polder" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0 -1.00 -1.00)
(save-previous-map-colour 37)
(get-map-colour 37)
