filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Youjia, Welcome to Coot version 0.8.6.1")
use_graphics_interface_state ()
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (186.30)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (12.60)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3m8b\3m8b.updated_refine_001.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8b/3m8b.updated_refine_001.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8b/3m8b.updated_refine_001.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3m8b\Polder_1\3m8b_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8b/Polder_1/3m8b_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
save_previous_map_colour (3)
get_map_colour (3)
graphics_molecule_bond_type (0)
close_molecule (1)
close_molecule (2)
close_molecule (3)
close_molecule (0)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3m8d\3m8d.updated_refine_001.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8d/3m8d.updated_refine_001.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8d/3m8d.updated_refine_001.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
save_previous_map_colour (5)
get_map_colour (5)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3m8d\Polder_1\3m8d_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3m8d/Polder_1/3m8d_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
save_previous_map_colour (7)
get_map_colour (7)
graphics_molecule_bond_type (4)
close_molecule (5)
close_molecule (6)
close_molecule (7)
close_molecule (4)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final-version-data\3rgn\3rgn.updated_refine_001.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/3rgn/3rgn.updated_refine_001.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/3rgn/3rgn.updated_refine_001.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\3rgn\Polder_1\3rgn_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/3rgn/Polder_1/3rgn_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
save_previous_map_colour (9)
get_map_colour (9)
save_previous_map_colour (11)
get_map_colour (11)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
graphics_molecule_bond_type (8)
close_molecule (8)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final-version-data\3rgn\3rgn.updated_refine_001.pdb", 1)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
graphics_molecule_bond_type (12)
close_molecule (12)
close_molecule (9)
close_molecule (10)
close_molecule (11)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3v3x\3v3x.updated_refine_001.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3v3x/3v3x.updated_refine_001.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3v3x/3v3x.updated_refine_001.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
save_previous_map_colour (14)
get_map_colour (14)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3v3x\Polder_1\3v3x_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3v3x/Polder_1/3v3x_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
save_previous_map_colour (16)
get_map_colour (16)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3v3x\Polder_2\3v3x_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3v3x/Polder_2/3v3x_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
save_previous_map_colour (17)
get_map_colour (17)
graphics_molecule_bond_type (13)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\3v3x\Polder_3\3v3x_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/3v3x/Polder_3/3v3x_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
save_previous_map_colour (18)
get_map_colour (18)
close_molecule (14)
close_molecule (15)
close_molecule (16)
close_molecule (17)
close_molecule (18)
close_molecule (13)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\5bmg\5bmg.updated_refine_001.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/5bmg/5bmg.updated_refine_001.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/5bmg/5bmg.updated_refine_001.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
save_previous_map_colour (20)
get_map_colour (20)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\5bmg\Polder_1\5bmg_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/5bmg/Polder_1/5bmg_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
save_previous_map_colour (22)
get_map_colour (22)
graphics_molecule_bond_type (19)
close_molecule (20)
close_molecule (21)
close_molecule (22)
close_molecule (19)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\1zyt\1zyt.updated_refine_001.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/1zyt/1zyt.updated_refine_001.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/1zyt/1zyt.updated_refine_001.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\add_protein\1zyt\Polder_1\1zyt_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/add_protein/1zyt/Polder_1/1zyt_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
save_previous_map_colour (24)
get_map_colour (24)
save_previous_map_colour (26)
get_map_colour (26)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
graphics_molecule_bond_type (23)
close_molecule (24)
close_molecule (25)
close_molecule (26)
close_molecule (23)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final-version-data\3ifx\3ifx.updated_refine_001.pdb", 1)
graphics_molecule_bond_type (27)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/3ifx.updated_refine_001.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/3ifx.updated_refine_001.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
close_molecule (28)
close_molecule (29)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/3ifx.updated_refine_001.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/3ifx.updated_refine_001.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\3ifx\Polder_1\3ifx_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/Polder_1/3ifx_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\3ifx\Polder_2\3ifx_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/3ifx/Polder_2/3ifx_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
save_previous_map_colour (30)
get_map_colour (30)
save_previous_map_colour (32)
get_map_colour (32)
save_previous_map_colour (33)
get_map_colour (33)
graphics_molecule_bond_type (27)
close_molecule (30)
close_molecule (31)
close_molecule (32)
close_molecule (33)
close_molecule (27)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final-version-data\5uui\5uui.updated_refine_001.pdb", 1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/5uui/5uui.updated_refine_001.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/5uui/5uui.updated_refine_001.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
save_previous_map_colour (35)
get_map_colour (35)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
manage_column_selector (C:\Users\youjia\Desktop\MTN_final-version-data\5uui\Polder_1\5uui_polder_map_coeffs.mtz)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final-version-data/5uui/Polder_1/5uui_polder_map_coeffs.mtz", "/crystal/dataset/mFo-DFc_polder", "/crystal/dataset/PHImFo-DFc_polder", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0, -1.00, -1.00)
save_previous_map_colour (37)
get_map_colour (37)
