filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Youjia, Welcome to Coot version 0.8.6.1")
use_graphics_interface_state ()
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (186.30)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (12.60)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (14.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
set_find_hydrogen_torsion (1)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final_version_data\add_protein\2cuu\2cuu.pdb", 1)
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final_version_data\add_protein\2cuu\2cuu.updated_refine_001.pdb", 1)
handle_read_draw_molecule_with_recentre ("C:\Users\youjia\Desktop\MTN_final_version_data\add_protein\2cuu\2cuu.updated_refine_001.pdb", 1)
set_molecule_bonds_colour_map_rotation (2, 140.00)
make_and_draw_map ("C:\Users\youjia\Desktop\MTN_final_version_data\add_protein\2cuu\Polder_1\2cuu_polder_map_coeffs.mtz", "mFo-DFc_polder", "PHImFo-DFc_polder", "", 0, 1)
set_contour_level_in_sigma ( 3.00)
make_and_draw_map ("C:\Users\youjia\Desktop\MTN_final_version_data\add_protein\2cuu\Polder_1\2cuu_polder_map_coeffs.mtz", "mFo-DFc_omit", "PHImFo-DFc_omit", "", 0, 1)
set_contour_level_in_sigma ( 3.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final_version_data/add_protein/2cuu/2cuu.updated_refine_001.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("C:/Users/youjia/Desktop/MTN_final_version_data/add_protein/2cuu/2cuu.updated_refine_001.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
graphics_molecule_bond_type (0)
graphics_molecule_bond_type (1)
graphics_molecule_bond_type (2)
