(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Youjia, Welcome to Coot version 0.8.6.1")
(use-graphics-interface-state)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 186.30)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 12.60)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 14.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(set-find-hydrogen-torsion 1)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final_version_data\add_protein\2cuu\2cuu.pdb" 1)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final_version_data\add_protein\2cuu\2cuu.updated_refine_001.pdb" 1)
(handle-read-draw-molecule-with-recentre "C:\Users\youjia\Desktop\MTN_final_version_data\add_protein\2cuu\2cuu.updated_refine_001.pdb" 1)
(set-molecule-bonds-colour-map-rotation 2 140.00)
(make-and-draw-map "C:\Users\youjia\Desktop\MTN_final_version_data\add_protein\2cuu\Polder_1\2cuu_polder_map_coeffs.mtz" "mFo-DFc_polder" "PHImFo-DFc_polder" "" 0 1)
(set-contour-level-in-sigma  3.00)
(make-and-draw-map "C:\Users\youjia\Desktop\MTN_final_version_data\add_protein\2cuu\Polder_1\2cuu_polder_map_coeffs.mtz" "mFo-DFc_omit" "PHImFo-DFc_omit" "" 0 1)
(set-contour-level-in-sigma  3.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final_version_data/add_protein/2cuu/2cuu.updated_refine_001.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "C:/Users/youjia/Desktop/MTN_final_version_data/add_protein/2cuu/2cuu.updated_refine_001.mtz" "FOFCWT" "PHFOFCWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(graphics-molecule-bond-type 0)
(graphics-molecule-bond-type 1)
(graphics-molecule-bond-type 2)
